# Generated by Django 5.2.6 on 2025-09-29 18:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('font_type', models.CharField(choices=[('latin', 'Latin'), ('arabic', 'Arabic'), ('mixed', 'Mixed (Latin + Arabic)')], max_length=20)),
                ('font_file', models.FileField(blank=True, help_text='Font file (TTF/OTF)', null=True, upload_to='fonts/')),
                ('is_system_font', models.BooleanField(default=False, help_text='Whether this is a system font or custom uploaded font')),
                ('supports_rtl', models.BooleanField(default=False, help_text='Whether this font supports right-to-left text')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Font Family',
                'verbose_name_plural': 'Font Families',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='FormattingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('business', 'Business'), ('legal', 'Legal'), ('government', 'Government'), ('personal', 'Personal')], max_length=20)),
                ('config', models.JSONField(help_text='Complete formatting configuration as JSON')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_premium', models.BooleanField(default=False, help_text='Whether this template requires a premium subscription')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formatting Template',
                'verbose_name_plural': 'Formatting Templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormattingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal'), ('A3', 'A3'), ('A5', 'A5')], default='A4', max_length=20)),
                ('page_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20)),
                ('margin_top', models.FloatField(default=72, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(144)])),
                ('margin_bottom', models.FloatField(default=72, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(144)])),
                ('margin_left', models.FloatField(default=72, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(144)])),
                ('margin_right', models.FloatField(default=72, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(144)])),
                ('body_font_size', models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(72)])),
                ('heading_font_size', models.FloatField(default=16, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(72)])),
                ('line_spacing', models.FloatField(default=1.5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)])),
                ('paragraph_spacing_before', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)])),
                ('paragraph_spacing_after', models.FloatField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)])),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('justify', 'Justify')], default='justify', max_length=20)),
                ('text_direction', models.CharField(choices=[('ltr', 'Left to Right'), ('rtl', 'Right to Left'), ('auto', 'Auto-detect')], default='auto', max_length=10)),
                ('include_header', models.BooleanField(default=False)),
                ('header_text', models.CharField(blank=True, max_length=500)),
                ('include_footer', models.BooleanField(default=True)),
                ('footer_text', models.CharField(blank=True, max_length=500)),
                ('include_page_numbers', models.BooleanField(default=True)),
                ('page_number_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_center', 'Bottom Center'), ('bottom_right', 'Bottom Right')], default='bottom_center', max_length=20)),
                ('first_line_indent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-72), django.core.validators.MaxValueValidator(72)])),
                ('hanging_indent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)])),
                ('column_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('column_spacing', models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)])),
                ('include_toc', models.BooleanField(default=False)),
                ('toc_depth', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('include_bibliography', models.BooleanField(default=False)),
                ('bibliography_style', models.CharField(choices=[('apa', 'APA'), ('mla', 'MLA'), ('chicago', 'Chicago'), ('harvard', 'Harvard')], default='apa', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_formatting_configs', to='formatting.fontfamily')),
                ('heading_font', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heading_formatting_configs', to='formatting.fontfamily')),
            ],
            options={
                'verbose_name': 'Formatting Configuration',
                'verbose_name_plural': 'Formatting Configurations',
            },
        ),
        migrations.CreateModel(
            name='UserFormattingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default formatting preset")),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formatting_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preset', to='formatting.formattingconfiguration')),
            ],
            options={
                'verbose_name': 'User Formatting Preset',
                'verbose_name_plural': 'User Formatting Presets',
                'ordering': ['-is_default', '-usage_count', 'name'],
            },
        ),
    ]
